DO $$ BEGIN
  CREATE TYPE "BusinessType" AS ENUM ('COMMERCE', 'RESTAURANT');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "ownerFirstName" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "ownerLastName" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "businessType" "BusinessType" NOT NULL DEFAULT 'COMMERCE';
