export const moduleKeys = [
  "POS",
  "inventario",
  "ventas",
  "reportes",
  "analytics avanzados",
  "auditoría",
  "exportaciones",
  "multi-sucursal analytics",
  "CRM",
  "delivery",
  "KDS",
  "customer display",
  "multi printer",
  "hardware advanced",
  "marketing",
  "campañas",
  "IA",
  "API",
  "WhatsApp",
  "multi-sucursal",
  "preventa móvil",
  "inventario distribuido",
  "caja avanzada",
  "transferencias",
  "propinas",
  "cupones",
  "combos",
  "usuarios",
  "roles",
  "tracking pedidos",
  "menú público",
  "sitio web",
  "mesas próximamente",
];
